raidprotect/raidprotect

README.md
Fix link which redirects to raidprotect.org instead of rust-lang.org
=> chore: fix incorrect link in readme

cache/src/cache.rs, cache/src/permission.rs
Improves the permission calculator:
- Only query the cache once and store values for different calculations (permissions, owner id, ...)
- Add `highest_role` and `RoleOrdering` to get a member's highest role
=> refactor(cache): improve permission calculator

cache/src/model/guild.rs, cache/src/permission.rs, cache/src/redis.rs
Adds a `current_member_permissions` method to the Redis cache, that returns `CachePermissions` for the bot member in a given guild.
=> feat(cache): current member cache permissions

cache/src/permission.rs, cache/src/redis.rs
- **Fix:** insert everyone role when fetching member roles for permission calculation.
- Add `GuildPermissions` to avoid fetching the guild from cache multiple times
=> fix(cache): everyone role in permissions

README.md, interaction/src/handle.rs, raidprotect/src/cluster.rs, raidprotect/src/config.rs
Discord shipped commands v2 that make global command rollout instant (see https://github.com/discord/discord-api-docs/pull/4896). The `command_guild` setting is thus no longer necessary for instant updates during development, commands are now always registered as global commands.
=> feat(interaction): register commands globally

.github/workflows/ci.yml, .rustfmt.toml, cache/src/process/event.rs, event/src/message/mod.rs, interaction/src/embed/error.rs, interaction/src/embed/kick.rs, interaction/src/handle.rs, model/src/mongodb.rs, util/src/serde.rs
Group imports using `rustfmt` unstable features. Nightly toolchain is now used in the CI to check formatting.
=> chore: group imports with rustfmt

.gitpod.yml, .vscode/extensions.json
rust-analyzer extension moved to Rust Lang organization, thus its id changed to `rust-lang.rust-analyzer`
=> chore: update rust-analyzer extension id

interaction/src/command/kick.rs, interaction/src/context.rs, model/src/collection/guild.rs
Add missing support for the `enforce_reason` configuration option to the kick command.
=> feat(interaction): support enforce_reason config

Cargo.lock, deny.toml, model/Cargo.toml, raidprotect/Cargo.toml
Use full dependencies versions in `Cargo.toml` (including patch version number). This PR also update dependencies to their latest version.
=> deps: use full versions in Cargo.toml

.github/workflows/ci.yml
GitHub supply chain security [now supports Rust](https://github.blog/2022-06-06-github-brings-supply-chain-security-features-to-the-rust-community/). This enables dependency review with [`dependency-review-action`](https://github.com/actions/dependency-review-action) on PRs.
=> ci: scan dependencies with github security

.github/workflows/ci.yml
`actions/dependency-review-action@v1` only works with `pull_request` event
=> fix(ci): skip dependencies review action on push

model/src/cache/redis.rs
Use named fields with MessagePack serialization. The cache will use more memory, but this allows for better error messages.
=> fix(cache): use named serialization

model/src/cache/model/component.rs, model/src/mongodb/modlog.rs, model/tests/modlog.rs, raidprotect/src/interaction/command/kick.rs, raidprotect/src/interaction/handle.rs
Adds the `PendingSanction` model for storing sanction state while waiting for the modal to be filled.
=> feat(cache): pending sanction model

Cargo.lock, model/Cargo.toml, raidprotect/Cargo.toml
Use [`webpki-roots`](https://lib.rs/crates/webpki-roots) (Mozilla's root certificates) instead of native ones. This standardizes TLS certificates across dependencies, since [`mongodb`](https://lib.rs/crates/mongodb) only supports webpki roots. It also improves security when running in out-of-date or minimal environments such as containers by embedding root certificates in the binary.
=> deps: use webpki instead of native tls certs

Cargo.lock, model/Cargo.toml, model/src/cache/redis.rs
Removes the zstd compression on the Redis cache.
- Compression makes debugging harder.
- Stored data is small, compression doesn't save much space (sometimes "compressed" data is larger than the original one).
- Reduce CPU usage.
=> refactor(cache): remove zstd compression

Cargo.lock, model/Cargo.toml, model/src/mongodb/client.rs
Remove the `zstd` dependency from `mongodb` (see #111) to improve compile times (`zstd-sys` takes almost 25 sec to compile on my computer). Use zlib compression instead, as `flate2` is already a `twilight-gateway` dependency.
=> deps: use zlib compression with mongodb

Cargo.lock, captcha/Cargo.toml, model/Cargo.toml, raidprotect/Cargo.toml, web/Cargo.toml
Upgrade dependencies to their latest version.
Notable upgrades:
- `twilight` 0.12.0 → 0.12.1 (multiple bug fixes)
- `mongodb` 2.2.2 → 2.3.0 (MongoDB v6 support)
`serde_with` has not been updated to the latest 2.0.0 version, since `mongodb` still depend on a 1.x version.
=> deps: upgrade to twilight 0.12.1

model/src/mongodb/guild.rs, model/tests/guild.rs, raidprotect/src/interaction/command/moderation/kick.rs, raidprotect/src/util/logs_channel.rs
Refactor the `Guild` configuration model:
- Remove the `Config` struct and move its field into `Guild`.
- Use a struct for moderation config, similar to the captcha configuration (#118).
- The bson representation is flattened with prefixes for each struct.
=> refactor: flatten configuration model

Cargo.lock, model/src/cache/model/interaction.rs, raidprotect/Cargo.toml, raidprotect/src/interaction/command/moderation/kick.rs, raidprotect/src/interaction/command/profile.rs, raidprotect/src/interaction/component/post_in_chat.rs, raidprotect/src/interaction/handle.rs, raidprotect/src/interaction/util.rs
Refactor how the bot handle incoming components.
The previous version stored all pending components in Redis. Since some components have no state, this PR parse the component `custom_id` instead and let the called component implementation retrieve state from Redis if required.
The `custom_id` format is now the following: `name` or `name:id`, where *name* is the name of the called component type, and *id* an optional id attached to it and used to retrieve state.
=> refactor(interaction): component handling

Cargo.lock, web/Cargo.toml
This PR update all dependencies to their latest version and fixes `cargo-deny` errors on the repo (see failed build of #130).
Notable changes:
- Update to chrono 0.4.20 to fix [RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159).
- Downgrade axum to 0.5.13 (0.5.14 was yanked due to a breaking change).
=> deps: update to latest chrono

.github/workflows/localazy-download.yml, .github/workflows/localazy-upload.yml, .gitignore, .vscode/settings.json, CONTRIBUTING.md, localazy.json, raidprotect/build.rs, raidprotect/src/event/message/handle.rs, raidprotect/src/interaction/embed/error.rs, raidprotect/src/interaction/embed/kick.rs, raidprotect/src/interaction/handle.rs, raidprotect/src/main.rs
Use Localazy to manage the bot translations: https://localazy.com/p/raidprotect-bot/
This PR also changes the default language to French, since this would allow reviewing English translations in Localazy (I'm not a native English speaker, so English translations may be incorrect).
=> feat: use localazy for translations

.vscode/settings.json, model/src/cache/http.rs, raidprotect/locales/fr.json, raidprotect/src/interaction/component/captcha/enable.rs, raidprotect/src/interaction/handle.rs, raidprotect/src/util/logs_channel.rs
- Automatically configure permission for the unverified role in all guild channels.
- Send a message in the logs channel after the captcha is created.
- Check if the captcha is not already enabled to avoid clicking the button twice.
=> feat: configure permissions for captcha role

Cargo.lock, deny.toml, model/Cargo.toml, raidprotect/Cargo.toml, web/Cargo.toml
Update dependencies to fix CI failures:
- Yanked crates `bytemuck` v1.12.0, `iana-time-zone` v0.1.44 and `plotters` v0.3.2 have been upgraded.
- `cargo-deny` configuration has been updated to warn on unmaintained crates (instead of denying them).
- Other dependencies have been updated to their latest version.
=> deps: update dependencies

raidprotect/src/cluster.rs, raidprotect/src/event/captcha/member_add.rs, raidprotect/src/event/message/handle.rs, raidprotect/src/event/process.rs, raidprotect/src/interaction/command/config/captcha.rs, raidprotect/src/interaction/command/moderation/kick.rs, raidprotect/src/interaction/component/captcha/disable.rs, raidprotect/src/interaction/component/captcha/enable.rs, raidprotect/src/interaction/component/captcha/verify.rs, raidprotect/src/interaction/component/post_in_chat.rs, raidprotect/src/interaction/handle.rs, raidprotect/src/interaction/response.rs, raidprotect/src/util/logs_channel.rs
- Remove unneeded `ClusterState` methods that can be replaced with struct fields access
- Remove most `Arc`s since each field is already wrapped with `Arc`
=> refactor: remove unneeded `ClusterState` methods

Cargo.lock, captcha/Cargo.toml, model/Cargo.toml, model/src/cache/discord/model/channel.rs, raidprotect/Cargo.toml, raidprotect/src/cluster.rs, web/Cargo.toml
- Replace `futures` dependency with `futures-util`
- Upgrade dependencies to their latest version
=> deps: replace futures with futures-util

raidprotect/src/interaction/command/config/mod.rs
`/config` command was allowed to be run in DMs.
=> fix(interaction): make config command guild only

raidprotect/src/interaction/command/config/captcha.rs, raidprotect/src/interaction/command/config/mod.rs, raidprotect/src/interaction/command/help.rs, raidprotect/src/interaction/command/moderation/kick.rs, raidprotect/src/interaction/command/profile.rs, raidprotect/src/interaction/component/captcha/disable.rs, raidprotect/src/interaction/component/captcha/enable.rs, raidprotect/src/interaction/component/captcha/verify.rs, raidprotect/src/interaction/component/post_in_chat.rs, raidprotect/src/interaction/handle.rs, raidprotect/src/interaction/util.rs
Add new `InteractionContext` and `GuildInteractionContext` types to store common fields parsed from interactions.
=> feat(interaction): add interaction context types

raidprotect/src/event/message/handle.rs, raidprotect/src/event/message/mod.rs, raidprotect/src/event/message/old_command.rs
Move the old command handler in it's own module to cleanup `handle.rs`. Some refactoring of the function has been made.
=> refactor(event): move old command handling
